// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmPrW4nv3UOonfS8qORm5_kSKjgG0UE4',
    appId: '1:37294812499:web:09f878ae3abc183985c5a6',
    messagingSenderId: '37294812499',
    projectId: 'habit-penguin-dev',
    authDomain: 'habit-penguin-dev.firebaseapp.com',
    storageBucket: 'habit-penguin-dev.firebasestorage.app',
    measurementId: 'G-13DDCEN297',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6SOtUlUG4_ZcdiuEdWlxH-Kau-UBcpdE',
    appId: '1:37294812499:android:c90bdd6ac2c1cb2c85c5a6',
    messagingSenderId: '37294812499',
    projectId: 'habit-penguin-dev',
    storageBucket: 'habit-penguin-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMiy_Mb_CGrcceq87-D4FijZipSB5H8YE',
    appId: '1:37294812499:ios:19ebbfc28df443a485c5a6',
    messagingSenderId: '37294812499',
    projectId: 'habit-penguin-dev',
    storageBucket: 'habit-penguin-dev.firebasestorage.app',
    iosBundleId: 'com.example.penguinTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMiy_Mb_CGrcceq87-D4FijZipSB5H8YE',
    appId: '1:37294812499:ios:19ebbfc28df443a485c5a6',
    messagingSenderId: '37294812499',
    projectId: 'habit-penguin-dev',
    storageBucket: 'habit-penguin-dev.firebasestorage.app',
    iosBundleId: 'com.example.penguinTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEmPrW4nv3UOonfS8qORm5_kSKjgG0UE4',
    appId: '1:37294812499:web:094374071007a38385c5a6',
    messagingSenderId: '37294812499',
    projectId: 'habit-penguin-dev',
    authDomain: 'habit-penguin-dev.firebaseapp.com',
    storageBucket: 'habit-penguin-dev.firebasestorage.app',
    measurementId: 'G-1YZGGYRPKM',
  );
}