// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT85eagXDWc_YhDyS0SXNnd9LwIv9si1M',
    appId: '1:680896848616:web:23ba452523ca9932a21f5d',
    messagingSenderId: '680896848616',
    projectId: 'penguin-timer-v1',
    authDomain: 'penguin-timer-v1.firebaseapp.com',
    storageBucket: 'penguin-timer-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmE3e0EeBrY2sGolvYB8Zrkmyed1fbp4',
    appId: '1:680896848616:android:8697648fa320f2a7a21f5d',
    messagingSenderId: '680896848616',
    projectId: 'penguin-timer-v1',
    storageBucket: 'penguin-timer-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaXIecdbmI-oPU8qJMVzkDPjNIlZPpR0',
    appId: '1:680896848616:ios:1225b4372f2a2534a21f5d',
    messagingSenderId: '680896848616',
    projectId: 'penguin-timer-v1',
    storageBucket: 'penguin-timer-v1.firebasestorage.app',
    iosBundleId: 'com.example.penguinTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFaXIecdbmI-oPU8qJMVzkDPjNIlZPpR0',
    appId: '1:680896848616:ios:1225b4372f2a2534a21f5d',
    messagingSenderId: '680896848616',
    projectId: 'penguin-timer-v1',
    storageBucket: 'penguin-timer-v1.firebasestorage.app',
    iosBundleId: 'com.example.penguinTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT85eagXDWc_YhDyS0SXNnd9LwIv9si1M',
    appId: '1:680896848616:web:326057dc460a641fa21f5d',
    messagingSenderId: '680896848616',
    projectId: 'penguin-timer-v1',
    authDomain: 'penguin-timer-v1.firebaseapp.com',
    storageBucket: 'penguin-timer-v1.firebasestorage.app',
  );
}
